plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\guilh\\Desktop\\gp-tech\\bella-site"
publishOrigin = "default"
base = "C:\\Users\\guilh\\Desktop\\gp-tech\\bella-site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]